version: 2.1

jobs:
  bundle:
    docker:
      - image: circleci/ruby:2.6.6
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundler-{{ checksum "diffcrypt.gemspec" }}-{{ .Environment.CACHE_VERSION }}
      - run:
          name: bundle install
          command: |
            gem install bundler -v '2.1.4'
            bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: bundler-{{ checksum "diffcrypt.gemspec" }}-{{ .Environment.CACHE_VERSION }}
          paths:
            - vendor/bundle

  test:
    docker:
      - image: circleci/ruby:2.6.6
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundler-{{ checksum "diffcrypt.gemspec" }}-{{ .Environment.CACHE_VERSION }}
      - run:
          name: bundle install
          command: |
            gem install bundler -v '2.1.4'
            bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: rake test
          command: |
            ./cc-test-reporter before-build
            bundle exec rake test
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
  rubocop:
    docker:
      - image: circleci/ruby:2.6.6
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundler-{{ checksum "diffcrypt.gemspec" }}-{{ .Environment.CACHE_VERSION }}
      - run:
          name: bundle install
          command: |
            gem install bundler -v '2.1.4'
            bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: rubocop
          command: bundle exec rubocop
          when: always

workflows:
  version: 2
  test:
    jobs:
      - bundle
      - test:
          requires:
            - bundle
      - rubocop:
          requires:
            - bundle
